import React from 'react';
import Head from 'next/head';

import OrderForm from '../components/Checkout/OrderForm';
import OrderSummary from '../components/Checkout/OrderSummary';

const checkout = () => {
    return (
        <div className='mt-5 mx-auto flex flex-col-reverse lg:flex-row gap-5'>
            <Head>
                <title>Checkout</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/gingercoons-Hightop-Sneakers.svg' />
            </Head>

            <div className='flex-1'>
                <OrderForm />
            </div>
            <div className='flex-1'>
                <OrderSummary />
            </div>
        </div>
    );
};

export default checkout;
