import Head from "next/head";
import Benefit from "../components/Benefit";
import Sliders from "../components/Sliders";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Sliders />
        <Benefit />
      </main>
    </div>
  );
}
