import axios from "axios";

import Head from "next/head";
import Benefit from "../components/Benefit";
import Sliders from "../components/Sliders";
import Header from "../components/Header";
import Categories from "../components/Categories";

export default function Home({ categories }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Sliders />
        <Benefit />
        <Categories categories={categories} />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await axios.get("http://localhost:9000/categories/v1");
  const categories = await res.data;

  return {
    props: {
      categories,
    },
  };
}
